name: AI PR Title and Description

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  pr-ai-helper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git fetch origin main
          git diff origin/main...HEAD > changes.diff
          head -n 200 changes.diff > short.diff

      - name: Generate PR Title and Description using Cohere
        id: cohere
        run: |
          if [ -z "$COHERE_API_KEY" ]; then
            echo "::error::COHERE_API_KEY is not set"
            exit 1
          fi

          # Escape diff for JSON safety
          DIFF=$(jq -Rs . < short.diff)

          # Call Cohere API
          RESPONSE=$(curl -s https://api.cohere.ai/v1/generate \
            -H "Authorization: Bearer $COHERE_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{
              \"model\": \"command-r\",
              \"max_tokens\": 300,
              \"temperature\": 0.7,
              \"prompt\": \"You are a GitHub bot. Based on this code diff, suggest a concise PR title (first line) and a detailed description (rest of the text). If no diff is found, generate a generic PR title and description.\\n\\n${DIFF}\"
            }" || echo "{}")

          echo "Cohere raw response: $RESPONSE"

          TEXT=$(echo "$RESPONSE" | jq -r '.generations[0].text // ""')

          if [ -z "$TEXT" ] || [ "$TEXT" = "null" ]; then
            echo "No text from Cohere, using fallback commit message."
            TITLE=$(git log -1 --pretty=%s)
            DESC=$(git log -1 --pretty=%b)
          else
            TITLE=$(echo "$TEXT" | head -n 1 | sed 's/^"//; s/"$//')
            DESC=$(echo "$TEXT" | tail -n +2 | sed 's/^"//; s/"$//')
          fi

          if [ -z "$TITLE" ]; then
            TITLE="Update PR"
          fi
          if [ -z "$DESC" ]; then
            DESC="Automated PR update by AI PR Helper"
          fi

          echo "TITLE=$TITLE" >> $GITHUB_ENV
          echo "DESC=$DESC" >> $GITHUB_ENV
          echo "title=$TITLE" >> $GITHUB_OUTPUT
          echo "desc=$DESC" >> $GITHUB_OUTPUT
        env:
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}

      - name: Update PR with AI-generated title and description
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ env.TITLE }}
          title: ${{ env.TITLE }}
          body: ${{ env.DESC }}
