name: Generate PR Title & Description

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  generate-pr-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install cohere

      - name: Get PR diff
        run: |
          git fetch origin main
          git diff origin/main...HEAD > changes.diff
          head -n 200 changes.diff > short.diff  # limit to 200 lines

      - name: Generate PR Title and Description
        id: generate_pr
        env:
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
        run: |
          python <<EOF
          import cohere, os, sys

          co = cohere.Client(os.getenv("COHERE_API_KEY"))
          diff = open("short.diff", "r", encoding="utf-8").read()

          if not diff.strip():
              print("::error::No code changes detected to summarize")
              sys.exit(1)

          prompt = f"Here is the code diff:\n{diff}\n\nGenerate:\nTITLE: <short title>\nDESCRIPTION: <detailed body>"

          response = co.generate(
              model="command-r-plus",
              prompt=prompt,
              max_tokens=300,
              temperature=0.3
          )

          text = response.generations[0].text.strip()
          title, desc = "", ""

          for line in text.splitlines():
              if line.startswith("TITLE:"):
                  title = line.replace("TITLE:", "").strip()
              elif line.startswith("DESCRIPTION:"):
                  desc = line.replace("DESCRIPTION:", "").strip()

          if not title or not desc:
              print("::error::Failed to generate title or description")
              sys.exit(1)

          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
              f.write(f"title={title}\n")
              f.write(f"desc={desc}\n")
          EOF

      - name: Update PR with AI-generated description
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update PR description"
          title: ${{ steps.generate_pr.outputs.title }}
          body: ${{ steps.generate_pr.outputs.desc }}
