name: AI PR Reviewer

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  ai-pr-reviewer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Cohere SDK
        run: pip install cohere

      - name: Generate diff file
        run: |
          git fetch origin main
          git checkout ${{ github.head_ref }}
          git diff origin/main...HEAD > changes.diff || echo "No changes" > changes.diff
          head -n 500 changes.diff > short.diff
          echo "Diff captured:"
          head -n 20 short.diff

      - name: AI Code Review
        id: review_pr
        env:
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          python <<EOF
          import os
          import cohere
          import requests
          import json

          SYSTEM_PROMPT = """\
          # System Role
          You are an expert software developer and code reviewer. Your task is to provide a constructive, professional, and concise code review for a given diff. Your feedback should focus on potential issues, best practices, and suggestions for improvement.

          # Task Specification
          Given a code diff as input, generate a code review comment.

          # Specifics and Context
          Your review should:
          - Summarize the main changes and their purpose.
          - Identify any potential bugs, performance issues, or security vulnerabilities.
          - Suggest improvements for code readability, maintainability, or design patterns.
          - Keep the tone professional and helpful.
          """

          co = cohere.Client(os.getenv("COHERE_API_KEY"))

          diff_text = open("short.diff", "r", encoding="utf-8").read()
          if not diff_text.strip():
              review_text = "No significant changes detected for review."
          else:
              prompt = f"{SYSTEM_PROMPT}\n\nInput (diff):\n{diff_text}\n\nOutput format: A concise, bulleted list of review points."
              try:
                  response = co.generate(
                      model="command-r-plus",
                      prompt=prompt,
                      max_tokens=500,
                      temperature=0.3
                  )
                  review_text = response.generations[0].text.strip()
              except Exception as e:
                  print("Error calling Cohere:", e)
                  review_text = "An error occurred while generating the review."

          # Post the review as a comment on the PR
          pr_number = os.getenv("PULL_REQUEST_NUMBER")
          if pr_number:
              owner_repo = os.getenv("GITHUB_REPOSITORY")
              github_token = os.getenv("GITHUB_TOKEN")
              url = f"https://api.github.com/repos/{owner_repo}/issues/{pr_number}/comments"
              headers = {
                  "Authorization": f"token {github_token}",
                  "Accept": "application/vnd.github.v3+json"
              }
              data = {
                  "body": f"### AI Code Review\n\n{review_text}"
              }
              response = requests.post(url, headers=headers, data=json.dumps(data))
              if response.status_code == 201:
                  print("Successfully posted AI review comment.")
              else:
                  print(f"Failed to post comment: {response.status_code} - {response.text}")
          else:
              print("PULL_REQUEST_NUMBER not found. Skipping comment post.")
          
          EOF