name: Branch Naming Convention Check

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  branch-naming:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        run: |
          BRANCH_NAME="${GITHUB_HEAD_REF}"
          if [[ ! "$BRANCH_NAME" =~ ^(feature|bugfix|hotfix)\/[a-z0-9._-]+$ ]]; then
            echo "Invalid branch name: $BRANCH_NAME"
            echo "Branch names must follow: feature/<name>, bugfix/<name>, or hotfix/<name>"
            exit 1
          fi
