name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and start containers with commit hash
        shell: pwsh
        run: |
          $COMMIT_HASH = "${{ github.sha }}"

          # Stop old containers
          docker compose down; if ($LASTEXITCODE -ne 0) { Write-Host "No containers running" }

          # Build backend with commit hash
          docker build -t my-backend:$COMMIT_HASH -t my-backend:latest .

          # Start new stack
          $env:DB_HOST="${{ secrets.DB_HOST }}"
          $env:DB_USER="${{ secrets.DB_USER }}"
          $env:DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
          $env:DB_NAME="${{ secrets.DB_NAME }}"

          docker compose up -d --force-recreate --build
